package com.example.news.presentation.components

object commen {
 val cuntryList = listOf(
         "India",
         "United States",
         "United Kingdom",
         "Canada",
         "Australia",
         "United Arab Emirates",
         "Saudi Arabia",
         "Qatar",
         "Pakistan",
         "Bangladesh",
         "Nepal",
         "Sri Lanka",
         "Afghanistan",
         "China",
         "Japan",
         "South Korea",
         "Singapore",
         "Malaysia",
         "Indonesia",
         "Thailand",
         "Vietnam",
         "Germany",
         "France",
         "Italy",
         "Spain",
         "Netherlands",
         "Sweden",
         "Switzerland",
         "Russia",
         "Ukraine",
         "Israel",
         "Palestine",
         "Iran",
         "Iraq",
         "Turkey",
         "Egypt",
         "South Africa",
         "Nigeria",
         "Brazil",
         "Mexico",
         "Argentina"
        )

    val countryCodeMap = mapOf(

        "India" to "in",
        "United States" to "us",
        "United Kingdom" to "gb",
        "Canada" to "ca",
        "Australia" to "au",
        "United Arab Emirates" to "ae",
        "Saudi Arabia" to "sa",
        "Qatar" to "qa",
        "Pakistan" to "pk",
        "Bangladesh" to "bd",
        "Nepal" to "np",
        "Sri Lanka" to "lk",
        "Afghanistan" to "af",
        "China" to "cn",
        "Japan" to "jp",
        "South Korea" to "kr",
        "Singapore" to "sg",
        "Malaysia" to "my",
        "Indonesia" to "id",
        "Thailand" to "th",
        "Vietnam" to "vn",
        "Germany" to "de",
        "France" to "fr",
        "Italy" to "it",
        "Spain" to "es",
        "Netherlands" to "nl",
        "Sweden" to "se",
        "Switzerland" to "ch",
        "Russia" to "ru",
        "Ukraine" to "ua",
        "Israel" to "il",
        "Palestine" to "ps",
        "Iran" to "ir",
        "Iraq" to "iq",
        "Turkey" to "tr",
        "Egypt" to "eg",
        "South Africa" to "za",
        "Nigeria" to "ng",
        "Brazil" to "br",
        "Mexico" to "mx",
        "Argentina" to "ar"
    )

    val categories = listOf(
        "top",
        "business",
        "crime",
        "domestic",
        "education",
        "entertainment",
        "environment",
        "food",
        "health",
        "lifestyle",
        "politics",
        "science",
        "sports",
        "technology",
        "tourism",
        "world",
        "other"
    )

    val menuOption = listOf(
        "Profile",
        "Important",
        "Setting",
        "Terms & Policy",
        "Help",
        "about",
    )
}